# Generated by Django 5.2.9 on 2026-01-14 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latin', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('meaning', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('repName', models.CharField(max_length=64)),
                ('repNameSort', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('dateUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('dateUpdated', models.DateField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.member')),
            ],
            options={
                'permissions': [('manager', 'full db management access')],
            },
        ),
        migrations.CreateModel(
            name='Fungi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=15)),
                ('species', models.CharField(max_length=64)),
                ('variety', models.CharField(max_length=64)),
                ('commonName', models.CharField(max_length=128)),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField()),
                ('genusFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.genus')),
                ('groupFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.group')),
                ('creatorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_creator', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_updater', to='managementApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('reportingName', models.CharField(max_length=64)),
                ('gridRef', models.CharField(max_length=10)),
                ('county', models.CharField(max_length=20)),
                ('VC', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('country', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=64)),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField()),
                ('creatorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Site_creator', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Site_updater', to='managementApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=15)),
                ('dateFound', models.DateField()),
                ('dateEntered', models.DateField(auto_now_add=True)),
                ('sentBMS', models.BooleanField()),
                ('dateSentBMS', models.DateField()),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField()),
                ('firstRecord', models.CharField(choices=[('S', 'Site'), ('B', 'Bucks'), ('D', 'Database')], max_length=1)),
                ('litRef', models.CharField(max_length=64)),
                ('DNATest', models.BooleanField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('assoc1FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Record_assoc1', to='managementApp.association')),
                ('assoc2FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Record_assoc2', to='managementApp.association')),
                ('assoc3FK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Record_assoc3', to='managementApp.association')),
                ('collectorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_collector', to='managementApp.member')),
                ('confirmerFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_confirmer', to='managementApp.member')),
                ('fungusFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.fungi')),
                ('identifierFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_identifier', to='managementApp.member')),
                ('recorderFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_recorder', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_updater', to='managementApp.member')),
                ('siteId', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.site')),
                ('substrFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_substr', to='managementApp.substrate')),
            ],
        ),
    ]
