# Generated by Django 5.2.9 on 2026-02-26 16:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latin', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fungi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=15, unique=True)),
                ('genus', models.CharField(max_length=64)),
                ('species', models.CharField(max_length=64)),
                ('variety', models.CharField(max_length=64)),
                ('group', models.CharField(max_length=64)),
                ('fullName', models.CharField(max_length=196)),
                ('commonName', models.CharField(max_length=128)),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('meaning', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('repName', models.CharField(max_length=64)),
                ('repNameSort', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('dateUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('initials', models.CharField(max_length=5, unique=True)),
                ('dateUpdated', models.DateField()),
                ('isDeleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FungiArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GBChkLst', models.BooleanField()),
                ('groupOld', models.CharField(max_length=64, null=True)),
                ('interpretCode', models.IntegerField(null=True)),
                ('DJSCode', models.CharField(max_length=10, null=True)),
                ('authority', models.CharField(max_length=128, null=True)),
                ('BAPspecies', models.BooleanField()),
                ('fungiFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.fungi')),
            ],
        ),
        migrations.CreateModel(
            name='FungiCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentFungus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.fungi')),
            ],
        ),
        migrations.AddField(
            model_name='fungi',
            name='currentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_current', to='managementApp.fungicurrent'),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.member')),
            ],
            options={
                'permissions': [('manager', 'full db management access')],
            },
        ),
        migrations.AddField(
            model_name='fungi',
            name='creatorFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_creator', to='managementApp.member'),
        ),
        migrations.AddField(
            model_name='fungi',
            name='updaterFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_updater', to='managementApp.member'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=15, unique=True)),
                ('dateFound', models.DateField()),
                ('dateEntered', models.DateField(auto_now_add=True)),
                ('sentBMS', models.BooleanField(default=False)),
                ('dateSentBMS', models.DateField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateUpdated', models.DateField()),
                ('firstRecord', models.CharField(choices=[('S', 'Site'), ('B', 'Bucks'), ('D', 'Database'), ('N', 'None')], max_length=1)),
                ('litRef', models.CharField(blank=True, max_length=64, null=True)),
                ('DNATest', models.BooleanField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('knownDup', models.BooleanField(default=False)),
                ('assoc1FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_assoc1', to='managementApp.association')),
                ('assoc2FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_assoc2', to='managementApp.association')),
                ('assoc3FK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_assoc3', to='managementApp.association')),
                ('collectorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_collector', to='managementApp.member')),
                ('confirmerFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_confirmer', to='managementApp.member')),
                ('fungusFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.fungicurrent')),
                ('identifierFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_identifier', to='managementApp.member')),
                ('recorderFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_recorder', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_updater', to='managementApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='RecordArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repFungus', models.CharField(max_length=15)),
                ('repFungusLocked', models.BooleanField()),
                ('sense', models.CharField(max_length=1, null=True)),
                ('ecoSys', models.CharField(max_length=128, null=True)),
                ('appox', models.BooleanField()),
                ('morph', models.CharField(max_length=64, null=True)),
                ('herbarium', models.CharField(max_length=64, null=True)),
                ('herbRef', models.CharField(max_length=64, null=True)),
                ('photoLoc', models.CharField(max_length=64, null=True)),
                ('BMSDupInd', models.BooleanField()),
                ('BMSHold', models.BooleanField()),
                ('BMSRecNo', models.IntegerField(null=True)),
                ('BMSForay', models.BooleanField()),
                ('BMSMisident', models.BooleanField()),
                ('BMSSenderNo', models.IntegerField(null=True)),
                ('BMSdate', models.DateField(null=True)),
                ('batchRemarks', models.TextField(null=True)),
                ('foray', models.TextField(null=True)),
                ('origin', models.CharField(max_length=64, null=True)),
                ('uniqueFlat', models.CharField(max_length=64, null=True)),
                ('DRecUnique', models.IntegerField(null=True)),
                ('DRecSpecimenNumber', models.CharField(max_length=10, null=True)),
                ('DRecMore', models.CharField(max_length=10, null=True)),
                ('DRecSpecimen', models.CharField(max_length=20, null=True)),
                ('DRecCulture', models.CharField(max_length=20, null=True)),
                ('DRecRecordNumber', models.CharField(max_length=10, null=True)),
                ('DRecRecordedAs', models.CharField(max_length=256, null=True)),
                ('DRec2005', models.BooleanField()),
                ('RecMsg2', models.CharField(max_length=32, null=True)),
                ('recFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.record')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('reportingName', models.CharField(max_length=64)),
                ('gridRef', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('VC', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('country', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=64)),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField(auto_now_add=True)),
                ('creatorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Site_creator', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Site_updater', to='managementApp.member')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='siteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.site'),
        ),
        migrations.AddField(
            model_name='record',
            name='substrFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_substr', to='managementApp.substrate'),
        ),
    ]
