# Generated by Django 5.2.9 on 2026-09-16 16:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('latin', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fungi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=196, unique=True)),
                ('englishName', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=64)),
                ('taxonGroup', models.CharField(max_length=64)),
                ('currentTVK', models.CharField(max_length=64)),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('meaning', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('repName', models.CharField(max_length=64)),
                ('repNameSort', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('dateUpdated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MemberLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Substrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='FungiArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=15, unique=True)),
                ('GBChkLst', models.BooleanField()),
                ('groupOld', models.CharField(max_length=64, null=True)),
                ('interpretCode', models.IntegerField(null=True)),
                ('DJSCode', models.CharField(max_length=10, null=True)),
                ('authority', models.CharField(max_length=128, null=True)),
                ('BAPspecies', models.BooleanField()),
                ('fungiFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.fungi')),
            ],
        ),
        migrations.CreateModel(
            name='FungiCurrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentFungus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.fungi')),
            ],
        ),
        migrations.AddField(
            model_name='fungi',
            name='currentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fungi_current', to='managementApp.fungicurrent'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('fullName', models.CharField(max_length=196)),
                ('initials', models.CharField(max_length=10)),
                ('dateUpdated', models.DateField()),
                ('isDeleted', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('manager', 'full db management access'), ('member', 'access to view db')],
            },
        ),
        migrations.AddField(
            model_name='fungi',
            name='creatorFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_creator', to='managementApp.member'),
        ),
        migrations.AddField(
            model_name='fungi',
            name='updaterFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Fungi_updater', to='managementApp.member'),
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=15, unique=True)),
                ('substrate', models.CharField(max_length=128)),
                ('assoc1', models.CharField(blank=True, max_length=128)),
                ('assoc2', models.CharField(blank=True, max_length=128)),
                ('assoc3', models.CharField(blank=True, max_length=128)),
                ('dateFound', models.DateField()),
                ('dateEntered', models.DateField(auto_now_add=True)),
                ('exported', models.BooleanField(default=False)),
                ('dateExported', models.DateField(null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('dateUpdated', models.DateField()),
                ('firstRecord', models.CharField(choices=[('S', 'Site'), ('B', 'Bucks'), ('D', 'Database'), ('N', 'None')], max_length=1)),
                ('litRef', models.CharField(blank=True, max_length=64, null=True)),
                ('DNATest', models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], max_length=7, null=True)),
                ('DNAseq', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fungi_photos')),
                ('certainty', models.CharField(choices=[('Certain', 'Certain'), ('Likely', 'Likely'), ('Uncertain', 'Uncertain')], default='Certain', max_length=9)),
                ('collectorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_collector', to='managementApp.member')),
                ('confirmerFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_confirmer', to='managementApp.member')),
                ('fungusFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.fungicurrent')),
                ('identifierFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_identifier', to='managementApp.member')),
                ('photographerFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_photographer', to='managementApp.member')),
                ('recorderFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_recorder', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Record_updater', to='managementApp.member')),
            ],
        ),
        migrations.CreateModel(
            name='RecordArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repFungus', models.CharField(max_length=15)),
                ('repFungusLocked', models.BooleanField()),
                ('sense', models.CharField(max_length=1, null=True)),
                ('ecoSys', models.CharField(max_length=128, null=True)),
                ('appox', models.BooleanField()),
                ('morph', models.CharField(max_length=64, null=True)),
                ('herbarium', models.CharField(max_length=64, null=True)),
                ('herbRef', models.CharField(max_length=64, null=True)),
                ('photoLoc', models.CharField(max_length=64, null=True)),
                ('BMSDupInd', models.BooleanField()),
                ('BMSHold', models.BooleanField()),
                ('BMSRecNo', models.IntegerField(null=True)),
                ('BMSForay', models.BooleanField()),
                ('BMSMisident', models.BooleanField()),
                ('BMSSenderNo', models.IntegerField(null=True)),
                ('BMSdate', models.DateField(null=True)),
                ('batchRemarks', models.TextField(null=True)),
                ('foray', models.TextField(null=True)),
                ('origin', models.CharField(max_length=64, null=True)),
                ('uniqueFlat', models.CharField(max_length=64, null=True)),
                ('DRecUnique', models.IntegerField(null=True)),
                ('DRecSpecimenNumber', models.CharField(max_length=10, null=True)),
                ('DRecMore', models.CharField(max_length=10, null=True)),
                ('DRecSpecimen', models.CharField(max_length=20, null=True)),
                ('DRecCulture', models.CharField(max_length=20, null=True)),
                ('DRecRecordNumber', models.CharField(max_length=10, null=True)),
                ('DRecRecordedAs', models.CharField(max_length=256, null=True)),
                ('DRec2005', models.BooleanField()),
                ('RecMsg2', models.CharField(max_length=32, null=True)),
                ('recFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.record')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('gridRef', models.CharField(max_length=20)),
                ('county', models.CharField(max_length=20)),
                ('VC', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('type', models.CharField(max_length=64)),
                ('remarks', models.TextField()),
                ('dateUpdated', models.DateField(auto_now_add=True)),
                ('creatorFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Site_creator', to='managementApp.member')),
                ('updaterFK', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='Site_updater', to='managementApp.member')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='siteFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='managementApp.site'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['VC'], name='managementA_VC_9b4827_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['dateFound'], name='managementA_dateFou_718190_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['dateFound', 'siteFK'], name='managementA_dateFou_472a52_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['dateFound', 'recorderFK'], name='managementA_dateFou_e56c6f_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['fungusFK', 'siteFK'], name='managementA_fungusF_92bc92_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['collectorFK', 'dateFound'], name='managementA_collect_b66c32_idx'),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['identifierFK', 'dateFound'], name='managementA_identif_83e808_idx'),
        ),
    ]
