# Generated by Django 5.2.9 on 2026-08-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='certainty',
            field=models.CharField(choices=[('Certain', 'Certain'), ('Likely', 'Likely'), ('Uncertain', 'Uncertain')], default='Certain', max_length=9),
        ),
    ]
