# Generated by Django 5.2.9 on 2026-06-10 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungi',
            name='currentName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fungi_current', to='managementApp.fungicurrent'),
        ),
        migrations.AlterField(
            model_name='record',
            name='DNATest',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No'), ('P', 'Pending')], default='P', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, default='no_image.png', null=True, upload_to=''),
        ),
    ]
