# Generated by Django 5.2.9 on 2026-03-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='record',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
