# Generated by Django 5.2.9 on 2026-01-15 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungiArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GBChkLst', models.BooleanField()),
                ('groupOld', models.CharField(max_length=64, null=True)),
                ('interpretCode', models.IntegerField(null=True)),
                ('DJSCode', models.CharField(max_length=10, null=True)),
                ('authority', models.CharField(max_length=128, null=True)),
                ('BAPspecies', models.BooleanField()),
                ('fungiFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.fungi')),
            ],
        ),
        migrations.CreateModel(
            name='RecordArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repFungus', models.CharField(max_length=15)),
                ('repFungusLocked', models.BooleanField()),
                ('sense', models.CharField(max_length=1, null=True)),
                ('ecoSys', models.CharField(max_length=128, null=True)),
                ('appox', models.BooleanField()),
                ('morph', models.CharField(max_length=64, null=True)),
                ('herbarium', models.CharField(max_length=64, null=True)),
                ('herbRef', models.CharField(max_length=64, null=True)),
                ('photoLoc', models.CharField(max_length=64, null=True)),
                ('BMSDupInd', models.BooleanField()),
                ('BMSHold', models.BooleanField()),
                ('BMSRecNo', models.IntegerField(null=True)),
                ('BMSForay', models.BooleanField()),
                ('BMSMisident', models.BooleanField()),
                ('BMSSenderNo', models.IntegerField(null=True)),
                ('BMSdate', models.DateField()),
                ('batchRemarks', models.TextField(null=True)),
                ('foray', models.TextField(null=True)),
                ('origin', models.CharField(max_length=64, null=True)),
                ('uniqueFlat', models.CharField(max_length=64, null=True)),
                ('DRecUnique', models.IntegerField(null=True)),
                ('DRecSpecimenNumber', models.CharField(max_length=10, null=True)),
                ('DRecMore', models.CharField(max_length=10, null=True)),
                ('DRecSpecimen', models.CharField(max_length=20, null=True)),
                ('DRecCulture', models.CharField(max_length=20, null=True)),
                ('DRecRecordNumber', models.CharField(max_length=10, null=True)),
                ('DRecRecordedAs', models.CharField(max_length=256, null=True)),
                ('DRec2005', models.BooleanField()),
                ('RecMsg2', models.CharField(max_length=32, null=True)),
                ('recFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='managementApp.record')),
            ],
        ),
    ]
