# Generated by Django 5.2.9 on 2026-03-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_record_lat_record_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='site',
            name='lon',
            field=models.FloatField(default=0.0),
        ),
    ]
