# Generated by Django 5.2.9 on 2026-01-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_fungiarchive_recordarchive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fungi',
            name='uniqueCode',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='uniqueCode',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
