# Generated by Django 5.2.9 on 2026-06-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_alter_fungi_currentname_alter_record_dnatest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='DNATest',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], max_length=7),
        ),
    ]
