# Generated by Django 5.2.9 on 2026-08-11 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0002_record_certainty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='dateSentBMS',
            new_name='dateExported',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='sentBMS',
            new_name='exported',
        ),
    ]
