# Generated by Django 5.2.9 on 2026-06-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_alter_record_dnatest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='DNATest',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Pending', 'Pending')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
