# Generated by Django 5.2.9 on 2026-01-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_alter_fungi_uniquecode_alter_record_uniquecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='siteId',
            new_name='siteFK',
        ),
        migrations.AlterField(
            model_name='record',
            name='DNATest',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='firstRecord',
            field=models.CharField(choices=[('S', 'Site'), ('B', 'Bucks'), ('D', 'Database'), ('N', 'None')], max_length=1),
        ),
        migrations.AlterField(
            model_name='record',
            name='litRef',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
