# Generated by Django 5.2.9 on 2026-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_rename_datesentbms_record_dateexported_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
            ],
        ),
    ]
