# Generated by Django 5.2.9 on 2026-03-19 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0003_site_lat_site_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='dayOfYear',
            field=models.IntegerField(default=-1000),
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['dateFound', 'dayOfYear'], name='managementA_dateFou_a5a28b_idx'),
        ),
    ]
