# Generated by Django 5.2.9 on 2026-03-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0004_record_dayofyear_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='record',
            name='managementA_dateFou_a5a28b_idx',
        ),
        migrations.AddIndex(
            model_name='record',
            index=models.Index(fields=['-dateFound', 'dayOfYear'], name='managementA_dateFou_0c6c47_idx'),
        ),
    ]
