# Generated by Django 5.2.9 on 2026-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0004_rename_siteid_record_sitefk_alter_record_dnatest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='genus',
            field=models.CharField(default='hi', max_length=64),
            preserve_default=False,
        ),
    ]
