# Generated by Django 5.2.9 on 2026-06-11 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0004_alter_record_dnatest_alter_record_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='photographerFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_photographer', to='managementApp.member'),
        ),
    ]
