# Generated by Django 5.2.9 on 2026-01-19 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0005_fungi_genus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungi',
            name='genusFK',
        ),
    ]
