# Generated by Django 5.2.9 on 2026-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0005_remove_record_managementa_datefou_a5a28b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='capRadius',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fungi',
            name='colourDarkness',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='fungi',
            name='height',
            field=models.FloatField(null=True),
        ),
    ]
