# Generated by Django 5.2.9 on 2026-06-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0005_record_photographerfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='assoc1FK',
        ),
        migrations.RemoveField(
            model_name='record',
            name='assoc2FK',
        ),
        migrations.RemoveField(
            model_name='record',
            name='assoc3FK',
        ),
        migrations.RemoveField(
            model_name='record',
            name='substrFK',
        ),
        migrations.AddField(
            model_name='record',
            name='assoc1',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='assoc2',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='assoc3',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='substrate',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
