# Generated by Django 5.2.9 on 2026-06-27 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0006_remove_record_assoc1fk_remove_record_assoc2fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='assoc1',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='assoc2',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='assoc3',
            field=models.CharField(blank=True, default='', max_length=128),
            preserve_default=False,
        ),
    ]
