# Generated by Django 5.2.9 on 2026-01-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0006_remove_fungi_genusfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fungi',
            name='groupFK',
        ),
        migrations.AddField(
            model_name='fungi',
            name='group',
            field=models.CharField(default='hi', max_length=64),
            preserve_default=False,
        ),
    ]
