# Generated by Django 5.2.9 on 2026-04-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0006_fungi_capradius_fungi_colourdarkness_fungi_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='centroid',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddIndex(
            model_name='fungi',
            index=models.Index(fields=['centroid'], name='managementA_centroi_2bea60_idx'),
        ),
    ]
