# Generated by Django 5.2.9 on 2026-04-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0007_fungi_centroid_fungi_managementa_centroi_2bea60_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='FungiCentroids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capRadius', models.FloatField(null=True)),
                ('colourDarkness', models.FloatField(null=True)),
                ('height', models.FloatField(null=True)),
            ],
        ),
    ]
