# Generated by Django 5.2.9 on 2026-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0007_alter_record_assoc1_alter_record_assoc2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='DNAseq',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
