# Generated by Django 5.2.9 on 2026-01-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0007_remove_fungi_groupfk_fungi_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='dateUpdated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
