# Generated by Django 5.2.9 on 2026-01-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0008_alter_site_dateupdated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='gridRef',
            field=models.CharField(max_length=20),
        ),
    ]
