# Generated by Django 5.2.9 on 2026-01-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0009_alter_site_gridref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='dateSentBMS',
            field=models.DateField(null=True),
        ),
    ]
