# Generated by Django 5.2.9 on 2026-01-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0010_alter_record_datesentbms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordarchive',
            name='BMSdate',
            field=models.DateField(null=True),
        ),
    ]
