# Generated by Django 5.2.9 on 2026-01-27 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0011_alter_recordarchive_bmsdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='latin',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
