# Generated by Django 5.2.9 on 2026-01-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0012_alter_association_latin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=16),
        ),
    ]
