# Generated by Django 5.2.9 on 2026-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0013_alter_site_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='initials',
            field=models.CharField(default='BS', max_length=5),
            preserve_default=False,
        ),
    ]
