# Generated by Django 5.2.9 on 2026-02-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0014_member_initials'),
    ]

    operations = [
        migrations.AddField(
            model_name='fungi',
            name='fullName',
            field=models.CharField(default='No', max_length=196),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='initials',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
