# Generated by Django 5.2.9 on 2026-02-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0015_fungi_fullname_alter_member_initials_alter_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='sentBMS',
            field=models.BooleanField(default=False),
        ),
    ]
