# Generated by Django 5.2.9 on 2026-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0016_alter_record_sentbms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='remarks',
            field=models.TextField(null=True),
        ),
    ]
