# Generated by Django 5.2.9 on 2026-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0018_alter_record_assoc1fk_alter_record_assoc2fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fungi/'),
        ),
    ]
