# Generated by Django 5.2.9 on 2026-02-16 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0019_alter_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, default='no_cover.png', upload_to=''),
        ),
    ]
