# Generated by Django 5.2.9 on 2026-02-18 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementApp', '0020_alter_record_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='assoc1FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_assoc1', to='managementApp.association'),
        ),
        migrations.AlterField(
            model_name='record',
            name='assoc2FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_assoc2', to='managementApp.association'),
        ),
        migrations.AlterField(
            model_name='record',
            name='assoc3FK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='Record_assoc3', to='managementApp.association'),
        ),
        migrations.AlterField(
            model_name='record',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='record',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
